Repository ember-cli/babel-plugin-htmlbars-inline-precompile, pull requests merged in 2020-05, with the labels that each got.

#209 Add Node 14 to CI.
  .github/workflows/nodejs.yml
Labels: internal

#208 Add ability to transfer compilation errors into runtime.
  __tests__/tests.js
  index.js
Labels: enhancement

#210 Drop Node 8 support.
  .github/workflows/nodejs.yml
  package.json
Labels: breaking

#211 Update release automation dependencies and settings.
  RELEASE.md
  package.json
  yarn.lock
Labels: internal

#215 Add support for hbs(`...`)
  __tests__/tests.js
  index.js
Labels: bug

#216 Avoid assuming ember-template-compiler result is JSON
  __tests__/tests.js
  index.js
Labels: bug, enhancement
